[package]
name = "irisqo"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Runtime
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7" }
futures = "0.3"
# JSON libs
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
http-serde = "1.1"
# Web libs
axum = "0.6"
tower-http = { version = "0.4.0", features = ["trace"] }
hyper = { version = "0.14", features = ["full"] }

# Configuration & Observability
dotenv = "0.15.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
# DB
sqlx = { version = "0.6", features = [
    "runtime-tokio-native-tls",
    "postgres",
    "macros",
    "uuid",
    "chrono",
    "json",
] }
# sqlb = "0.0.8"
# Types
thiserror = "1.0"
uuid = { version = "1.3", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
problemdetails = { version = "0.2", features = ["axum"] }
whoami = { version = "1.4" }

[dev-dependencies]
anyhow = "1"
