[package]
name = "irisqo"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Runtime
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7" }
futures = "0.3"
async-channel = "1.8"
# JSON libs
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
http-serde = "1.1"
serde_urlencoded = "0.7"
# Web libs
axum = "0.6"
tower = "0.4"
tower-http = { version = "0.4.0", features = ["trace"] }
hyper = { version = "0.14", features = ["full"] }
url = { version = "2.3"}
# Configuration & Observability
dotenv = "0.15.0"
opentelemetry = { version = "0.19", features = ["rt-tokio", "metrics"] }
opentelemetry-http = { version = "0.8", features = ["hyper", "tokio"] }
tracing = { version =  "0.1.37" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-opentelemetry = { version = "0.18" }
# DB
sqlx = { version = "0.6", features = [
    "runtime-tokio-native-tls",
    "postgres",
    "macros",
    "uuid",
    "chrono",
    "json",
] }
# sqlb = "0.0.8"
# Types
thiserror = "1.0"
uuid = { version = "1.3", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
problemdetails = { version = "0.2", features = ["axum"] }
whoami = { version = "1.4" }

[dev-dependencies]
anyhow = "1"
