@host=http://localhost:8102

###
GET {{host}}

###
# @name req
GET {{host}}/to/{{host}}/error?_retry=3&_delay=5

###
@job-id = {{req.response.headers.job-id}}
@schedule-id = {{req.response.headers.schedule-id}}

###
GET {{host}}/api/v1/jobs/{{job-id}}

###
GET {{host}}/api/v1/jobs/{{job-id}}/history

###
GET {{host}}/api/v1/jobs/{{job-id}}/result

###
GET {{host}}/api/v1/jobs/{{job-id}}/result/raw

###
GET {{host}}/api/v1/instances

###
GET {{host}}/api/v1/schedules?limit=100

###
GET {{host}}/api/v1/schedules/{{schedule-id}}

###
PUT {{host}}/api/v1/schedules/{{schedule-id}}

###
GET {{host}}/error